version: '3'
services:
  ngrok:
    container_name: ngrok
    image: wernight/ngrok:latest
    ports:
      - ${NGROK_PORT:-4040}:4040
    environment:
      # うまくいかない
      NGROK_PORT: 127.0.0.1:3000