apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: deploy-slack-chatgpt
build:
  local:
    push: true #GCRにbuildしたimageをpushする
  artifacts:
    - image: gcr.io/sample-328713/slack-chatgpt #ここにpushする？
      context: .
      docker:
        dockerfile: Dockerfile
profiles:
  - name: prod
    manifests:
      rawYaml:
        - run-prod.yaml #Cloud Runサービス定義の名前を指定。任意の数の成果物を"リリース"としてまとめる
deploy:
  cloudrun: {}
  # options:
  #   allowUnauthenticated: true #未認証のアクセスを許可する
